FROM --platform=$BUILDPLATFORM golang:alpine AS builder
WORKDIR /go/src/github.com/bluenviron/mediamtx
ARG TARGETOS TARGETARCH BRANCH
ENV CGO_ENABLED=0
ENV GOOS=$TARGETOS
ENV GOARCH=$TARGETARCH

RUN set -ex \
  && echo "http://dl-cdn.alpinelinux.org/alpine/edge/community" >> /etc/apk/repositories \
  && apk update \
  && apk upgrade \
  && apk add git build-base make tzdata upx \
  && git clone -b $BRANCH --single-branch https://github.com/bluenviron/mediamtx /go/src/github.com/bluenviron/mediamtx \
  && go generate ./... \
  && mkdir -p /release/mediamtx \
  && go build -ldflags "-X github.com/bluenviron/mediamtx/internal/core.version=$BRANCH" -o /release/mediamtx/mediamtx \
  && upx --lzma /release/mediamtx/mediamtx \
  && cp  mediamtx.yml /release/mediamtx

FROM --platform=$TARGETPLATFORM alpine AS dist
RUN set -ex \
  && apk upgrade \
  && apk add --no-cache ffmpeg \
  && rm -rf /var/cache/apk/*

WORKDIR /mediamtx
COPY --from=builder /release/* /
ENTRYPOINT ["/mediamtx/mediamtx"]
