FROM --platform=$BUILDPLATFORM golang:alpine AS builder
WORKDIR /go/src/github.com/dolthub/dolt
ARG TARGETOS TARGETARCH BRANCH
ENV CGO_ENABLED=1
ENV GOOS=$TARGETOS
ENV GOARCH=$TARGETARCH

RUN set -ex \
  && echo "http://dl-cdn.alpinelinux.org/alpine/edge/community" >> /etc/apk/repositories \
  && apk update \
  && apk upgrade \
  && apk add git build-base make tzdata upx musl-dev gcc curl \
  && case "$TARGETOS" in \
      "linux") ;; \
      *) echo "ERROR: Unsupported OS: ${TARGETOS}"; exit 1 ;; \
  esac \
  && case "$TARGETARCH" in \
    "amd64") \
        FILE="x86_64-linux-musl-cross.tgz" \
        export CC="x86_64-linux-musl-gcc" \
    ;; \
    "arm64") \
        FILE="aarch64-linux-musl-cross.tgz" \
        export CC="aarch64-linux-musl-gcc" \
    ;; \
    *) \
        echo "ERROR: Unsupported CPU architecture: ${TARGETARCH}"; \
        exit 1 \
    ;; \
  esac \
  && curl -L -o ${FILE} "https://musl.nn.ci/${FILE}" \
  && tar xf ${FILE} --strip-components 1 -C /usr/local \
  && rm -f ${FILE} \
  &&  git clone -b $BRANCH --single-branch https://github.com/eiblog/eiblog . \
  && go build -v -trimpath -ldflags "--extldflags '-static -fpic' -w -s" -o eiblog ./cmd/eiblog \
  && upx --best --lzma eiblog \
  && mkdir -p /app \
  && cp eiblog /app

# 第二阶段：运行（使用目标平台的最小化镜像）
FROM --platform=$TARGETPLATFORM alpine AS dist
RUN set -ex \
  && apk upgrade \
  && apk add --no-cache ca-certificates tzdata \
  && rm -rf /var/cache/apk/*

WORKDIR /app
COPY --from=builder /app /app/
ENV TZ=Asia/Shanghai
EXPOSE 9000
CMD ["/app/eiblog"]
