FROM alpine:latest AS builder
ARG BRANCH
ENV CGO_ENABLED=0

RUN set -ex \
  && echo "http://dl-cdn.alpinelinux.org/alpine/edge/community" >> /etc/apk/repositories \
  && apk update \
  && apk upgrade \
  && apk add --no-cache bash curl jq gcc git go musl-dev upx make coreutils libcap

RUN git clone --single-branch https://github.com/0xERR0R/blocky /app

WORKDIR /app/

# Download dependencies (cached layer unless go.mod/go.sum change)
RUN go mod download

RUN builtAt="$(date +'%F %T %z')" \
  && version="${BRANCH}" \
  && ldflags=" \
    -w -s \
	  -X github.com/0xERR0R/blocky/util.Version=$version \
	  -X github.com/0xERR0R/blocky/util.BuildTime=$builtAt \
	  -X github.com/0xERR0R/blocky/util.Architecture=General" \
  && echo "[INFO] Building binary..." \
  && go build -v -trimpath -ldflags "$ldflags" -o /release/opt/blocky/blocky . \
  && upx --lzma --best /release/opt/blocky/blocky \
  && echo "[INFO] Build completed successfully"

FROM alpine:latest

USER 100
WORKDIR /opt/blocky

COPY --from=builder /release /

ENV BLOCKY_CONFIG_FILE=/opt/blocky/config.yml

ENTRYPOINT ["/opt/blocky/blocky"]

HEALTHCHECK --start-period=1m --timeout=3s CMD ["/opt/blocky/blocky", "healthcheck"]
