FROM alpine AS builder
ARG TARGETARCH BRANCH

# 安装必要的工具和依赖
RUN set -ex \
  && echo "http://dl-cdn.alpinelinux.org/alpine/edge/community" >> /etc/apk/repositories \
  && apk update \
  && apk upgrade \
  && apk add --no-cache git upx build-base curl openssl-dev openssl-libs-static linux-headers aria2 pkgconf \
                        make tzdata ca-certificates bash clang20 clang20-dev clang20-libclang tree \
                        clang20-static llvm20-dev llvm20-static \
                        rust cargo nodejs npm

ENV LIBCLANG_PATH=/usr/lib/
ENV LD_LIBRARY_PATH=/usr/lib
ENV BINDGEN_EXTRA_CLANG_ARGS="-I/usr/include/clang/20/include"

# 克隆源码
RUN git clone -b $BRANCH --single-branch https://github.com/pymumu/smartdns /build/smartdns

WORKDIR /build/smartdns

# Step 1: 执行构建脚本
RUN set -ex && \
    npm config set allow-remote all && \
    npm config set allow-git all && \
    if [ "$TARGETARCH" = "amd64" ]; then \
      ARCH_NAME="x86_64"; \
    else \
      ARCH_NAME="aarch64"; \
    fi && \
    sh ./package/build-pkg.sh --platform linux --arch $ARCH_NAME --with-ui

# Step 2: 解压构建产物
RUN set -ex && \
    cd package && \
    tar -xvf *.tar.gz && \
    tree .

# Step 3: 准备发布目录
RUN set -ex && \
    mkdir -p /release/var/log /release/run /release/usr/sbin /release/usr/lib /release/wwwroot /release/etc/smartdns

# Step 4: 复制文件
RUN set -ex && \
    cp package/smartdns/usr/sbin/smartdns /release/usr/sbin/ -a && \
    cp package/smartdns/usr/local/lib/smartdns/smartdns_ui.so /release/usr/lib -a && \
    cp -r package/smartdns/usr/share/smartdns/wwwroot /release && \
    cp -r package/smartdns/etc /release

# Step 5: 压缩二进制文件
RUN set -ex && \
    upx --best --lzma /release/usr/sbin/smartdns && \
    upx --best --lzma /release/usr/lib/smartdns_ui.so

# Step 6: 示例配置
RUN cat > /release/etc/smartdns/smartdns.conf <<EOF
bind 0.0.0.0:53

server 223.5.5.5
server 119.29.29.29
server 1.1.1.1

server-https https://dns.alidns.com/dns-query
server-https https://doh.pub/dns-query
server-https https://cloudflare-dns.com/dns-query

cache-size 50000
cache-persist yes
cache-file /var/lib/smartdns.cache
local-ttl 120

force-qtype-SOA 65
log-level info
log-size 128K

# Enable dashboard plugin
plugin /usr/lib/smartdns_ui.so

# Dashboard plugin config
smartdns-ui.ip http://[::]:6080

smartdns-ui.www-root /wwwroot
smartdns-ui.token-expire 86400
smartdns-ui.user admin
smartdns-ui.password admin

smartdns-ui.max-query-log-age 6048000
smartdns-ui.enable-terminal yes
data-dir /var/lib/smartdns
EOF

# Step 7: 清理构建目录
RUN rm -rf /build

FROM alpine AS dist

COPY --from=builder /release/ /

RUN set -ex \
  && echo "http://dl-cdn.alpinelinux.org/alpine/edge/community" >> /etc/apk/repositories \
  && apk update \
  && apk upgrade \
  && apk add --no-cache openssl libgcc ca-certificates tzdata \
  && chmod +x /usr/sbin/smartdns

EXPOSE 53/udp 53/tcp

CMD ["/usr/sbin/smartdns", "-f", "-x", "-c", "/etc/smartdns/smartdns.conf"]
