FROM --platform=$BUILDPLATFORM python:3.11.9-alpine3.20 AS base
ARG THREADS="4"
ARG SHA=""
ARG TARGETOS TARGETARCH BRANCH TOML11_BRANCH LIBCRON_BRANCH

# build minimized
WORKDIR /
RUN set -xe && apk update
RUN apk add --no-cache --virtual .build-tools git g++ build-base linux-headers cmake python3
RUN apk add --no-cache --virtual .build-deps curl-dev rapidjson-dev pcre2-dev yaml-cpp-dev
# 安装 Python 和 pip
RUN apk update && \
    apk add --no-cache python3 py3-pip
RUN python3 -m ensurepip
RUN pip3 install --upgrade pip
RUN python3 -m pip install gitpython
RUN python3 -m pip install pysocks
    
FROM base AS builder
ARG THREADS="4"
ARG SHA=""
ARG TARGETOS TARGETARCH BRANCH TOML11_BRANCH LIBCRON_BRANCH

# build minimized
WORKDIR /

RUN git clone https://github.com/ftk/quickjspp --depth=1 && \
    cd quickjspp && \
    git submodule update --init && \
    cmake -DCMAKE_BUILD_TYPE=Release . && \
    make quickjs -j $THREADS && \
    install -d /usr/lib/quickjs/ && \
    install -m644 quickjs/libquickjs.a /usr/lib/quickjs/ && \
    install -d /usr/include/quickjs/ && \
    install -m644 quickjs/quickjs.h quickjs/quickjs-libc.h /usr/include/quickjs/ && \
    install -m644 quickjspp.hpp /usr/include && \
    cd /
RUN git clone -b $LIBCRON_BRANCH --single-branch https://github.com/PerMalmberg/libcron --depth=1 && \
    cd libcron && \
    git submodule update --init && \
    cmake -DCMAKE_BUILD_TYPE=Release . && \
    make libcron -j $THREADS && \
    install -m644 libcron/out/Release/liblibcron.a /usr/lib/ && \
    install -d /usr/include/libcron/ && \
    install -m644 libcron/include/libcron/* /usr/include/libcron/ && \
    install -d /usr/include/date/ && \
    install -m644 libcron/externals/date/include/date/* /usr/include/date/ && \
    cd /
RUN git clone -b $TOML11_BRANCH --single-branch https://github.com/ToruNiina/toml11 --branch="v3.7.1" --depth=1 && \
    cd toml11 && \
    cmake -DCMAKE_CXX_STANDARD=11 . && \
    make install -j $THREADS && \
    cd /
RUN git clone -b $BRANCH --single-branch https://github.com/tindy2013/subconverter --depth=1 \
 && cd subconverter \
 && sed -i 's/DivineEngine/keelewang/g' scripts/rules_config.conf \
 && python3 scripts/update_rules.py -c scripts/rules_config.conf \
 && cmake -DCMAKE_BUILD_TYPE=Release . \
 && make -j $THREADS \
 && mkdir -p /build/app && mkdir -p /build/usr/bin \
 && mv /subconverter/base /build/app \
 && mv /subconverter/subconverter /build/usr/bin

# build final image
FROM --platform=$BUILDPLATFORM alpine:3.20
RUN apk add --no-cache --virtual subconverter-deps pcre2 libcurl yaml-cpp

COPY --from=builder /build /

# set entry
WORKDIR /app
CMD ["subconverter"]

EXPOSE 5500/tcp
