FROM --platform=$BUILDPLATFORM golang:alpine AS builder
WORKDIR /go/src/github.com/hiddify/hiddify-core
ARG TARGETOS TARGETARCH BRANCH
ENV CGO_ENABLED=0
ENV GOOS=$TARGETOS
ENV GOARCH=$TARGETARCH

RUN set -ex \
  && echo "http://dl-cdn.alpinelinux.org/alpine/edge/community" >> /etc/apk/repositories \
  && apk update \
  && apk upgrade \
  && apk add --no-cache git upx unzip curl \
  && git clone -b ${BRANCH} --single-branch https://github.com/hiddify/hiddify-core /go/src/github.com/hiddify/hiddify-core \
  && curl -L -o webui.zip  https://github.com/hiddify/Yacd-meta/archive/gh-pages.zip \
  && unzip -d ./ -q webui.zip \
  && rm webui.zip \
  && mkdir -p /release/app /release/etc/hiddify \
  && mv Yacd-meta-gh-pages /release/app/webui \
  && ldflags="\
     -buildid= \
     -w -s " \
  && tags="with_gvisor,with_quic,with_wireguard,with_ech,with_utls,with_clash_api,with_grpc,with_dhcp,with_low_memory,with_conntrack" \
  && go build -v -trimpath -ldflags "--extldflags '-static -fpic' $ldflags" -tags=$tags -o /release/app/hiddify ./cmd/main \
  && upx --lzma /release/app/hiddify \
  && cat > /release/app/hiddify.json << EOF
{
    "region":"other",
    "service-mode": "proxy",
    "log-level": "info",
    "resolve-destination": true,
    "ipv6-mode": "prefer_ipv4",
    "remote-dns-address": "tcp://1.1.1.1",
    "remote-dns-domain-strategy": "",
    "direct-dns-address": "1.1.1.1",
    "direct-dns-domain-strategy": "",
    "mixed-port": 12334,
    "local-dns-port": 16450,
    "tun-implementation": "mixed",
    "mtu": 9000,
    "strict-route": false,
    "connection-test-url": "https://www.gstatic.com/generate_204",
    "url-test-interval": 600,
    "enable-clash-api": true,
    "clash-api-port": 16756,
    "bypass-lan": false,
    "allow-connection-from-lan": true,
    "enable-fake-dns": false,
    "enable-dns-routing": true,
    "independent-dns-cache": true,
    "enable-tls-fragment": false,
    "tls-fragment-size": "20-70",
    "tls-fragment-sleep": "10-30",
    "enable-tls-mixed-sni-case": false,
    "enable-tls-padding": false,
    "tls-padding-size": "15-30",
    "enable-mux": false,
    "mux-padding": false,
    "mux-max-streams": 4,
    "mux-protocol": "h2mux",
    "enable-warp": false,
    "warp-detour-mode": "outbound",
    "warp-license-key": "",
    "warp-clean-ip": "auto",
    "warp-port": 0,
    "warp-noise": "5-10",
    "warp-noise-delay": "20-200"
  }
EOF

FROM --platform=$TARGETPLATFORM alpine AS dist

COPY --from=builder /release /

#RUN set -ex \
# && apk update \
# && apk upgrade --no-cache \
# && apk add --no-cache bash \
# && rm -rf /var/cache/apk/*

WORKDIR /app

ENV TZ=Asia/Shanghai
ENV PUID=0 PGID=0 UMASK=022

EXPOSE 2334
EXPOSE 2335
EXPOSE 6756
EXPOSE 6450

CMD [ "/app/hiddify", "run", "--config", "/etc/hiddify/hiddify.json" ]
