FROM golang:alpine AS builder
WORKDIR /go/src/github.com/sagernet/sing-box
ARG TARGETOS TARGETARCH BRANCH
ENV CGO_ENABLED=1
ENV GOOS=$TARGETOS
ENV GOARCH=$TARGETARCH
ARG GOAMD64_VERSION=v1
ENV GOAMD64=$GOAMD64_VERSION

RUN set -ex \
  && echo "http://dl-cdn.alpinelinux.org/alpine/edge/community" >> /etc/apk/repositories \
  && apk update \
  && apk upgrade \
  && apk add git build-base gcc make tzdata musl-dev upx ca-certificates bash openssl curl xz aria2 \
  && case "$TARGETOS" in \
      "linux") ;; \
      *) echo "ERROR: Unsupported OS: ${TARGETOS}"; exit 1 ;; \
  esac \
  && case "$TARGETARCH" in \
    "amd64") \
        FILE="x86_64-linux-musl-cross.tgz" \
        export CC="x86_64-linux-musl-gcc" \
    ;; \
    "arm64") \
        FILE="aarch64-linux-musl-cross.tgz" \
        export CC="aarch64-linux-musl-gcc" \
    ;; \
    *) \
        echo "ERROR: Unsupported CPU architecture: ${TARGETARCH}"; \
        exit 1 \
    ;; \
  esac \
  && aria2c -x 16 -s 16 -o ${FILE} "https://musl.nn.ci/${FILE}" \
  && tar xf ${FILE} --strip-components 1 -C /usr/local \
  && rm -f ${FILE} \
  && git clone -b $BRANCH --single-branch https://github.com/sagernet/sing-box /go/src/github.com/sagernet/sing-box \
  && export VERSION=$(go run ./cmd/internal/read_tag) \
  && go build -v -trimpath -tags with_v2ray_api,with_grpc,with_tailscale,with_gvisor,with_quic,with_dhcp,with_wireguard,with_utls,with_acme,with_clash_api \
    -o /go/bin/sing-box \
    -ldflags "-X \"github.com/sagernet/sing-box/constant.Version=$VERSION\" -s -w -buildid=" \
    ./cmd/sing-box \
  && upx --lzma /go/bin/sing-box

FROM alpine AS dist
RUN set -ex \
  && apk upgrade \
  && apk add bash tzdata ca-certificates \
  && rm -rf /var/cache/apk/*

COPY --from=builder /go/bin/sing-box /usr/local/bin/sing-box
ENTRYPOINT [ "/usr/local/bin/sing-box" ]
