FROM alpine:latest AS builder
ARG TARGETARCH
ARG TARGETPLATFORM

RUN apk add --no-cache ca-certificates wget \
    && wget -O /paperly https://git.hbox.de5.net/mxu/paperly-docs/raw/branch/main/paperly-${TARGETARCH} \
    && chmod +x /paperly

FROM alpine:latest AS dist

RUN apk add --no-cache \
        bash \
        tzdata \
        ca-certificates

COPY --from=builder /paperly /app/paperly

ENTRYPOINT ["/app/paperly"]
