FROM --platform=$BUILDPLATFORM golang:alpine AS builder
WORKDIR /go/src/github.com/daeuniverse/dae
ARG TARGETOS TARGETARCH BRANCH
ENV CGO_ENABLED=0
ENV GOOS=$TARGETOS
ENV GOARCH=$TARGETARCH

ENV GOFLAGS="-mod=readonly"

RUN set -ex \
  && echo "http://dl-cdn.alpinelinux.org/alpine/edge/community" >> /etc/apk/repositories \
  && apk update \
  && apk upgrade \
  && apk add --no-cache git upx llvm15 clang15 make \
  && ln -s /usr/bin/clang15 /usr/bin/clang \
  && which clang \
  && clang --version \
  && git clone -b $BRANCH --single-branch https://github.com/daeuniverse/dae /go/src/github.com/daeuniverse/dae \
  && git submodule update --init \
  && export CLANG=clang-15 \
  && make OUTPUT=dae GOFLAGS="-buildvcs=false" CC=clang CGO_ENABLED=0 \
  && upx --lzma dae \
  && mkdir -p /release/usr/local/bin /etc/dae /usr/local/share/dae \
  && mv dae /release/usr/local/bin/ \
  && wget -O /release/usr/local/share/dae/geoip.dat https://github.com/v2fly/geoip/releases/latest/download/geoip.dat \
  && wget -O /release/usr/local/share/dae/geosite.dat https://github.com/v2fly/domain-list-community/releases/latest/download/dlc.dat \
  && cp install/empty.dae /release/etc/dae/config.dae \
  && chmod 0600 /release/etc/dae/config.dae

FROM --platform=$BUILDPLATFORM alpine

COPY --from=builder /release /

CMD ["dae"]

ENTRYPOINT ["dae", "run", "-c", "/etc/dae/config.dae"]
