FROM --platform=$BUILDPLATFORM golang:alpine AS builder
WORKDIR /go/src/github.com/eiblog/eiblog
ARG TARGETOS TARGETARCH BRANCH
ENV CGO_ENABLED=1
ENV GOOS=$TARGETOS
ENV GOARCH=$TARGETARCH

RUN set -ex \
  && echo "http://dl-cdn.alpinelinux.org/alpine/edge/community" >> /etc/apk/repositories \
  && apk update \
  && apk upgrade \
  && apk add git build-base make tzdata upx musl-dev \
  && case "$TARGETOS" in \
      "linux") ;; \
      *) echo "ERROR: Unsupported OS: ${TARGETOS}"; exit 1 ;; \
  esac \
  && case "$TARGETARCH" in \
    "amd64") \
        GCC="gcc" \
    ;; \
    "arm64") \
        GCC="gcc-aarch64-linux-musl" \
    ;; \
    *) \
        echo "ERROR: Unsupported CPU architecture: ${TARGETARCH}"; \
        exit 1 \
    ;; \
  esac \
  && apk add ${GCC} \
  && git clone -b $BRANCH --single-branch https://github.com/eiblog/eiblog /go/src/github.com/eiblog/eiblog \
  && go build -tags prod -ldflags '-extldflags "-static"' -o eiblog "./cmd/eiblog" \
  && upx --best --lzma /go/src/github.com/eiblog/eiblog/eiblog \
  && mkdir -p /app \
  && cp /go/src/github.com/eiblog/eiblog/eiblog /app \
  && cp /go/src/github.com/eiblog/eiblog/conf /app/conf -R \
  && cp /go/src/github.com/eiblog/eiblog/conf /app/assets -R \
  && cp /go/src/github.com/eiblog/eiblog/website /app/website -R \
  && rm /app/conf/README.md \
  && rm /app/assets/README.md \
  && rm /app/website/README.md

FROM --platform=$TARGETPLATFORM alpine AS dist
RUN set -ex \
  && apk upgrade \
  && apk add --no-cache curl grep \
  && rm -rf /var/cache/apk/*

WORKDIR /app
COPY --from=builder /usr/share/zoneinfo /usr/share/zoneinfo
ENV TZ=Asia/Shanghai
COPY --from=builder /app /app/
EXPOSE 9000
CMD ["/app/eiblog"]
