FROM golang:alpine AS builder
WORKDIR /go/src/github.com/dolthub/dolt
ARG TARGETOS TARGETARCH BRANCH
ENV CGO_ENABLED=1
ENV GOOS=$TARGETOS
ENV GOARCH=$TARGETARCH
ARG GOAMD64_VERSION=v1
ENV GOAMD64=$GOAMD64_VERSION

ENV CGO_CFLAGS="-I/usr/include -Wno-error=parentheses"
ENV CGO_CPPFLAGS="-I/usr/include"
ENV CGO_LDFLAGS="-L/usr/lib"

RUN set -ex \
  && echo "http://dl-cdn.alpinelinux.org/alpine/edge/community" >> /etc/apk/repositories \
  && apk update \
  && apk upgrade \
  && apk add --no-cache git build-base gcc make tzdata musl-dev upx ca-certificates bash openssl curl xz aria2 icu-dev icu-static \
  && case "$TARGETOS" in \
      "linux") ;; \
      *) echo "ERROR: Unsupported OS: ${TARGETOS}"; exit 1 ;; \
  esac \
  && case "$TARGETARCH" in \
    "amd64") \
        FILE="x86_64-linux-musl-cross.tgz" \
        export CC="x86_64-linux-musl-gcc" \
    ;; \
    "arm64") \
        FILE="aarch64-linux-musl-cross.tgz" \
        export CC="aarch64-linux-musl-gcc" \
    ;; \
    *) \
        echo "ERROR: Unsupported CPU architecture: ${TARGETARCH}"; \
        exit 1 \
    ;; \
  esac \
  && aria2c -x 16 -s 16 -o ${FILE} "https://musl.nn.ci/${FILE}" \
  && tar xf ${FILE} --strip-components 1 -C /usr/local \
  && rm -f ${FILE} \
  && test -f /usr/include/unicode/uregex.h \
  && find /usr/include -name uregex.h \
  && git clone -b $BRANCH --single-branch https://github.com/dolthub/dolt . \
  && cd go \
  && go build -v -trimpath -ldflags "-linkmode external -extldflags '-static -fpic' -w -s" -o /release/usr/local/bin/dolt ./cmd/dolt \
  && upx --best --lzma /release/usr/local/bin/dolt

RUN mkdir /release/docker-entrypoint-initdb.d

FROM alpine AS dist
RUN set -ex \
  && apk upgrade \
  && apk add --no-cache tini ca-certificates \
  && rm -rf /var/cache/apk/*

VOLUME /var/lib/dolt
COPY --from=builder /release /
EXPOSE 3306 33060
WORKDIR /var/lib/dolt
ENTRYPOINT ["/usr/local/bin/dolt", "sql-server"]

