FROM --platform=$BUILDPLATFORM golang:alpine AS builder
WORKDIR /go/src/github.com/jeessy2/ddns-go
ARG TARGETOS TARGETARCH BRANCH
ENV CGO_ENABLED=0
ENV GOOS=$TARGETOS
ENV GOARCH=$TARGETARCH

RUN set -ex \
  && echo "http://dl-cdn.alpinelinux.org/alpine/edge/community" >> /etc/apk/repositories \
  && apk update \
  && apk upgrade \
  && apk add git build-base make tzdata upx \
  && git clone -b $BRANCH --single-branch https://github.com/jeessy2/ddns-go /go/src/github.com/jeessy2/ddns-go \
  && make clean build \
  && upx --lzma /go/src/github.com/jeessy2/ddns-go/ddns-go \
  && mkdir /app \
  && cp /go/src/github.com/jeessy2/ddns-go/ddns-go /app

FROM --platform=$TARGETPLATFORM alpine AS dist
RUN set -ex \
  && apk upgrade \
  && apk add --no-cache curl grep \
  && rm -rf /var/cache/apk/*

WORKDIR /app
COPY --from=builder /usr/share/zoneinfo /usr/share/zoneinfo
ENV TZ=Asia/Shanghai
COPY --from=builder /app/ddns-go /app/ddns-go
EXPOSE 9876
ENTRYPOINT ["/app/ddns-go"]
CMD ["-l", ":9876", "-f", "300"]
