name: "Auto Build vlmcsd"

on:
  repository_dispatch:
    types: [Auto Build vlmcsd]
    
env:
  DOCKER_REPO: 'vlmcsd'
  GITHUB_REPO: 'Wind4/vlmcsd'
  DOCKER_FILE: 'Dockerfile-vlmcsd'
  APP_NAME: 'vlmcsd'

permissions:
  contents: write
  packages: write
  actions: write

jobs:
  process-dispatch:
    runs-on: ubuntu-latest
    name: "process dispatch"
    outputs:
      status: ${{ steps.check-repo-dispatch.outputs.status }}
    steps:
      - name: check-repo-dispatch
        run: |
          if [ "${{ env.GITHUB_REPO }}" = "${{ github.event.client_payload.owner }}/${{ github.event.client_payload.repo }}" ]; then
            echo "status=success" >> $GITHUB_OUTPUT
          else
            echo "status=failure" >> $GITHUB_OUTPUT
          fi

          
  check-version:
    needs: process-dispatch
    if: ${{ needs.process-dispatch.outputs.status }} == 'success'
    runs-on: ubuntu-latest
    name: "check version"
    outputs:
      version: ${{ steps.get-version.outputs.version }}
      commit: ${{ steps.get-version.outputs.commit }}
    steps:
      - name: checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: check version
        id: get-version
        run: |
          releases=$(wget -qO- --tries=3 "https://api.github.com/repos/${{ env.GITHUB_REPO }}/commits?per_page=2" | jq -r ".[].sha")
          hash=$(grep -vm1 '-' <<< "$releases")
          shorthash=$(echo $hash | head -c 7)
          DATE=$(date "+%Y/%m/%d")
          COMMIT="Build ${{ env.APP_NAME }} git-$shorthash by Github Actions, $DATE"

          echo "version=${shorthash}" >> $GITHUB_OUTPUT
          echo "commit=$COMMIT" >> $GITHUB_OUTPUT

  
  create-release:
    needs: check-version
    runs-on: ubuntu-latest
    name: "Create release"
    env:
      VERSION: ${{ needs.check-version.outputs.version }}
      MSG: ${{ needs.check-version.outputs.commit }}
    steps:
      - name: checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: create release
        uses: shogo82148/actions-create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.APP_NAME }}-${{ env.VERSION }}
          release_name: ${{ env.APP_NAME }}-${{ env.VERSION }}
          body: ${{ env.MSG }}
          draft: false
          prerelease: false
          overwrite: true

  
  build-docker-image:
    needs: check-version
    runs-on: ubuntu-latest
    name: "build docker image"
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      VERSION: ${{ needs.check-version.outputs.version }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: Push images to Docker hub
        env:
          DOCKERHUB_REPOSITORY: ${{ secrets.DOCKER_USERNAME }}/${{ env.DOCKER_REPO }}
        uses: docker/build-push-action@v6
        with:
          push: true
          file: docker/${{ env.DOCKER_FILE }}
          platforms: linux/amd64, linux/arm64
          build-args: BRANCH=${{ env.VERSION }}
          tags: |
            ${{ env.DOCKERHUB_REPOSITORY }}:latest

  
  build-releases:
    needs: check-version
    name: build releases
    env:
      BINARY: vlmcsd
      VERSION: ${{ needs.check-version.outputs.version }}
      MSG: ${{ needs.check-version.outputs.commit }}
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
      CC_AMD64: gcc
      CC_ARM64: aarch64-linux-gnu-gcc

    strategy:
      matrix:
        target:
          - amd64
          - arm64
        include:
          - target: amd64
            host_os: ubuntu-latest
            artifact_name: vlmcsd-linux-amd64.zip
          - target: arm64
            host_os: ubuntu-latest
            artifact_name: vlmcsd-linux-arm64.zip
            
    runs-on: ${{ matrix.host_os }}

    steps:
      - name: checkout code
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0

      - name: install dependencies
        shell: bash
        run: |
          set -e  # 若有命令失败，则退出并报错
          sudo apt-get update
          sudo apt-get install -y git make build-essential gcc-aarch64-linux-gnu g++-aarch64-linux-gnu
          sudo rm -rf /var/lib/apt/lists/*

      - name: clone repository & compile
        run: |
          git clone --branch master --single-branch https://github.com/Wind4/vlmcsd
          cd vlmcsd
          if [ "${{ matrix.target }}" == "amd64" ]; then
            export CC=${CC_AMD64}
          elif [ "${{ matrix.target }}" == "arm64" ]; then
            export CC=${CC_ARM64}
          fi
          make CC=$CC vlmcsd
          mkdir -p ../release
          upx --lzma bin/${{ env.BINARY }}
          zip -j ../release/${{ matrix.artifact_name }} bin/${{ env.BINARY }}
          
      - name: upload binaries
        uses: actions/upload-artifact@v4.3.3
        with:
          name: ${{ matrix.artifact_name }}
          path: release/${{ matrix.artifact_name }}
        
      - name: upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          # A personal access token for the GitHub repository in which the release will be created and edited.
          # It is recommended to create the access token with the following scopes: `repo, user, admin:repo_hook`.
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: release/${{ matrix.artifact_name }}
          asset_name: ${{ matrix.artifact_name }}
          tag: ${{ env.APP_NAME }}-${{ env.VERSION }}
          overwrite: true
          body: ${{ env.MSG }}
          
  
  update-repo:
    needs:
      - check-version
      - create-release
      - build-docker-image
      - build-releases
    runs-on: ubuntu-latest
    name: "update repo"
    env:
      VERSION: ${{ needs.check-version.outputs.version }}
      COMMIT: ${{ needs.check-version.outputs.commit }}

    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}
          fetch-depth: 0

      - name: mark
        run: |
          sudo apt-get install -y jq
          
          git checkout --orphan tmp_work
          git branch -d main

          sed -i -E 's/(\|\s*${{ env.APP_NAME }}\s*\|)\s*\S+\s*\|/\1 git-${{ env.VERSION }} \|/' README.md

          # Update repos.json
          IFS='/' read -r owner repo <<< "${{ env.GITHUB_REPO }}"
          jq --arg owner "$owner" --arg repo "$repo" --arg new_version "${{ env.VERSION }}" \
              'map(if .owner == $owner and .repo == $repo then .version = $new_version else . end)' \
              .github/workflows/repos.json > update_repos.json
          mv update_repos.json .github/workflows/repos.json 

      - name: upload to repository
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: ${{ env.COMMIT }}
          create_branch: true
          branch: main
          push_options: --force

      - name: delete old workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          delete_workflow_pattern: "${{ env.APP_NAME }}"
          retain_days: 0
          keep_minimum_runs: 0
          delete_run_by_conclusion_pattern: "cancelled, skipped, success"
